# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accelerated gradient function for ARD
#'
#' @param inputs A matrix object. ARD census data (K x N).
#' @param outputs A matrix object. ARD survey data (K x M).
#' @param lambda_val A double. Initial lambda value.
#' @param Lipschitz String. Method for computing Lipschitz constant.
#' @param iterations Integer. Maximum number of iterations.
#' @param etol Double. Error tolerance.
#' @param gamma Double. Step size parameter.
#' @param symmetrized Boolean. Whether to symmetrize the output.
#' @param fixed_effects Boolean. Whether to use fixed effects.
#' @return An N x M matrix estimate of network connections.
#' @export
accel_nuclear_gradient_cpp <- function(inputs, outputs, lambda_val, Lipschitz = "regression", iterations = 5000L, etol = 1e-5, gamma = 2.0, symmetrized = TRUE, fixed_effects = FALSE) {
    .Call(`_nuclearARD_accel_nuclear_gradient_cpp`, inputs, outputs, lambda_val, Lipschitz, iterations, etol, gamma, symmetrized, fixed_effects)
}

compute_lipschitz <- function(inputs, outputs, lambda, L_bar, Z, gamma) {
    .Call(`_nuclearARD_compute_lipschitz`, inputs, outputs, lambda, L_bar, Z, gamma)
}

compute_iteration <- function(inputs, outputs, lambda, L_bar, Z, alpha, W, etol, fixed_effects_bool, fixed_effects_vector_min1) {
    .Call(`_nuclearARD_compute_iteration`, inputs, outputs, lambda, L_bar, Z, alpha, W, etol, fixed_effects_bool, fixed_effects_vector_min1)
}

nuclear_norm <- function(matrix) {
    .Call(`_nuclearARD_nuclear_norm`, matrix)
}

symmetrize <- function(matrix) {
    .Call(`_nuclearARD_symmetrize`, matrix)
}

matrix_OLS <- function(X, Y) {
    .Call(`_nuclearARD_matrix_OLS`, X, Y)
}

